name: Government GIS Job Hunter

on:
  workflow_dispatch:

  schedule:
    - cron: "0 15 * * *"

jobs:
  run-job-hunter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Job Hunter
        run: python main.py
